### PR TITLE
ĥ

### PR DESCRIPTION
**Pull request by ctrlcctrlv**
* Various build system improvements.
  * Build now requires install of xidel and GNU parallel.
* Moved ĥ's circumflex position.
* Fixed ĵ's circumflex position in certain ultracondensed weights.

### CODE REVIEW

**Comment by ctrlcctrlv** [comment]
Oh, I should justify this. Well, I can't. I tried over on Libertinus bug tracker once and made no friends:

- https://github.com/alerque/libertinus/issues/329

Put succinctly:

* I consider myself an authority on Esperanto typography;
* The version with the circumflex below the ascender height not only looks wrong to me but looks ugly to me, I'm not sure which is worse;
* Despite @alerque closing my issue I still feel this way and can never be convinced otherwise, no amount of sources will do so, but since I commissioned this font feel like I can ask you to move the circumflex on ĥ if I do the work of…doing that, as I did. :joy:

**Comment by ctrlcctrlv** [comment]
Oh, and I determined the positions in each case by copying ĵ into ĥ and then moving it such that the top of ȷ was even with the top of h, then deleting the j and previous circumflex.

image

**Comment by alerque** [comment]
First, I didn't close the issue on Libertinus, it is still open ;-)

Second, reading it now it seems somewhat bizarre to me now that adding the alternative anchor position as a stylistic alternative never came up in the Libertinus issue discussion. Even if we continue to disagree on what the default for the Libertinus family should be, would adding a stylistic alternative serve any purpose for you?

**Comment by ctrlcctrlv** [comment]
It sure would :o) I might use the font for writing Esperanto in that case.

**Comment by ctrlcctrlv** [comment]
The reason I've made this change is because I've been stress testing the font by using it as my system Sans…

image

And, tonight, finally, I broke as could not stand seeing the other (wrong :stuck_out_tongue:) ĥ so often, hahaha. So endeavored to patch this font. Font a much more…erm, _real_, issue in the process, the ĵ thing.

image

I could use a system serif that isn't as…unique, as Besley/MFEK Serif, yeah. And fontconfig lets me force a stylistic  alt always on so that's no issue.

**Comment by ctrlcctrlv** [comment]
(Obviously a man insane enough to commission fonts as a private individual is insane enough to care about this petty nonsense. :joy_cat:)

**Comment by EwonRael** [comment]
thanks for the strong circumflex opinions. I will draw my "ĥ" this way going forward

**Comment by EwonRael** [comment]
hey... 

FYI I went back and updated the position of the "top" anchor point in the "h" so that it would automatically generate the circumflexed h in the desirable way. I think generally this is the best way of doing things rather than manually moving the accent in the accented glyph. 

still should look the desired way tho

:)

**Comment by ctrlcctrlv** [comment]
oh okay that's fine :-) :+1: :tada: 

i actually normally only use that feature for first pass!

**Comment by ctrlcctrlv** [comment]
> thanks for the strong circumflex opinions. I will draw my "ĥ" this way going forward

note: only applies to ĥ. no opinion on ḃ or ḣ as i don't speak Irish Gaelic. most fonts have those below ascender, that's probably fine especially if they prefer it. :-)

**Comment by ctrlcctrlv** [comment]
let me know by the way if the build system changes cause any issues

i think you use arch (or manjaro?)

on either system the needed packages are:

* `aur/xidel`
* `extra/parallel`

**Pull request merged**
